name: safenest
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  mobile_scanner: ^7.0.0
  intl: ^0.18.0
  permission_handler: ^11.0.0
  flutter_dotenv: ^5.0.2 
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/safenest.png

flutter_native_splash:
  color: "#5271FF"
  image: assets/safenest.png
  color_dark: "#121212"
  image_dark: assets/safenest.png
  android_12:
    image: assets/safenest.png
    icon_background_color: "#ffffff"
    image_dark: assets/safenest.png
    icon_background_color_dark: "#121212"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/safenest.png" # Fixed path
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#5271FF"
